plugin:
  prefix: "&7[&5Ogre&3Dupe&7] &r"

chat:
  anti-swear:
    enabled: true
    whitelist:
      - glass
    blacklist:
      - ass
    leet-patterns:
      0: o
      1: i
      3: e
      4: a
      5: s
      6: g
      7: l
      "$": s
      "!": i
      "+": t
      "#": h
      "@": a
      "<": c
      V: u
      v: u
  anti-spam:
    enabled: true
    cooldown: 5
  anti-repeat:
    enabled: true
  anti-unicode:
    enabled: true

player:
  first-join-message: "%player% has joined the game for their first time!"
  join-message: "&e%player% has joined the game"
  quit-message: "&e%player% has left the game"
  on-join:
    - /spawn

server:
  command-spy-blacklist:
    - /dupe
    - /msg
    - /message
    - /w
    - /whisper
    - /tell
