plugin:
  prefix: "&7[&5Ogre&3Dupe&7] &r"

chat:
  anti-swear:
    enabled: true
    whitelist:
      - glass
    blacklist:
      - ass
  anti-spam:
    enabled: true
    cooldown: 5
  anti-repeat:
    enabled: true
  anti-unicode:
    enabled: true

player:
  first-join-message: "%player% has joined the game for their first time!"
  join-message: "&e%player% has joined the game"
  quit-message: "&e%player% has left the game"
  on-join:
    - /spawn

server:
  command-spy-blacklist:
    - /dupe
    - /msg
    - /message
    - /w
    - /whisper
    - /tell
