plugin:
  prefix: "&7[&5Ogre&3Dupe&7] &r"

chat:
  anti-swear:
    enabled: true
    whitelist:
      - d
    blacklist:
      - d
  anti-spam:
    enabled: true
    cooldown: 5
  anti-repeat:
    enabled: true
  anti-unicode:
    enabled: true

player:
  join-message: "&e%player% has joined the game"
  quit-message: "&e%player% has left the game"
  on-join:
    - /spawn

server:
  command-spy-blacklist:
    - /dupe
